services:
  db:
    image: mysql:8.4.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3306:3306
    networks:
      - app-networks
  api:
    build: .
    image: ogustavoress/api-consultas
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
  