name: Continuous Integration

on:
  push:
    branches:
      - develop
      - feature/**
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Execução de Testes Unitários
        run: mvn test

      - name: Empacotamento com Maven
        run: mvn package -DskipTests
