name: versionamento
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:

    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
        # Create a personal access token (PAT)
        # configure it as a GitHub action secret as `RELEASE_PLEASE_TOKEN`
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # it's a built-in strategy in release-please,
          # see "Action Inputs" for more options
          release-type: maven